name: Build iOS IPA

on:
  push:
    branches:
      - hai
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6'
          cache: true
          architecture: arm64

      # Chạy flutter pub get ở thư mục gốc project
      - name: Get Flutter dependencies
        working-directory: remotelensapp
        run: flutter pub get

      # Clean & Install CocoaPods
      - name: Clean old CocoaPods
        working-directory: remotelensapp/ios
        run: |
          pod deintegrate || true
          rm -rf Pods Podfile.lock

      - name: Install CocoaPods
        working-directory: remotelensapp/ios
        run: pod install --repo-update

      # Build IPA ở thư mục project
      - name: Build IPA (no codesign)
        working-directory: remotelensapp
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: remotelensapp-ios-ipa
          path: remotelensapp/build/ios/ipa/*.ipa
          retention-days: 7
