name: Build iOS IPA (No Sign)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2

      - name: 📦 Flutter pub get
        run: flutter pub get
        working-directory: remotelensapp

      - name: 🛠 Build iOS Simulator
        run: flutter build ios --release --simulator
        working-directory: remotelensapp

      - name: 📦 Create IPA
        run: |
          mkdir Payload
          cp -r build/ios/iphonesimulator/Runner.app Payload/
          zip -r app.ipa Payload
        working-directory: remotelensapp

      - name: 📤 Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: remotelensapp/app.ipa
