name: Build iOS IPA

on:
  push:
    branches:
      - hai
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'   # hoặc chỉ định '3.29.0' nếu bạn muốn fix version
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install CocoaPods
        working-directory: ios
        run: pod install

      - name: Build IPA (no codesign)
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: remotelensapp-ios-ipa
          path: build/ios/ipa/*.ipa
          retention-days: 7
